#    +------------- Docker-compose ---------------------+    
#    +                                                  +    
#    +   - myapp           : main container             +    
#    +   - mysql8          : mysql8 container           +    
#    +   - phpmyadmin      : phpmyadmin container       +    
#    +--------------------------------------------------+    









version: "3"
services:
  symfo:
    image: symfo:1.0
    container_name: myapp
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./app:/var/www/
    
  database:
    image: mysql:8.0
    ports:
      - 3307:3307
    container_name: mysql8

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    working_dir: "/app/db"
    volumes: 
      - ./mysql8:/app/db
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:8082
    container_name: phpmyadmin
    depends_on:
      - database
    links: 
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3307
    restart: always
    working_dir: "/app/phpmyadmin"
    volumes:
      - ./phpmyadmin:/app/phpmyadmin 